---
- name: Install dependencies
  package:
    name:
      - openjdk-8-jdk
      - wget
      - curl
    update_cache: true
    state: present
  become: true

- name: Create service user
  user:
    name: "{{ minecraft_service_user }}"
    system: true
    state: present
  become: true

- name: Create install folder
  file:
    path: "{{ minecraft_install_folder }}"
    owner: "{{ minecraft_service_user }}"
    group: "{{ minecraft_service_user }}"
    state: directory
    mode: 0744
  become: true

- name: Prepare the eula.txt file
  copy:
    src: "eula.txt"
    dest: "{{ minecraft_install_folder }}/eula.txt"
    owner: "{{ minecraft_service_user }}"
    group: "{{ minecraft_service_user }}"
    mode: 0744
  become: true
  notify:
    - restart minecraft-service

- name: Getting the server JAR file
  get_url:
    url: https://launcher.mojang.com/v1/objects/3dc3d84a581f14691199cf6831b71ed1296a9fdf/server.jar
    dest: "{{ minecraft_install_folder }}"
    owner: "{{ minecraft_service_user }}"
    group: "{{ minecraft_service_user }}"
    mode: 0744
  become: true
  notify:
    - restart minecraft-service

- name: Setting up server.properties file
  template:
    src: server.properties
    dest: "{{ minecraft_install_folder }}"
    owner: "{{ minecraft_service_user }}"
    group: "{{ minecraft_service_user }}"
    mode: 0744
  become: true
  notify:
    - restart minecraft-service

- name: Setting up startup script
  template:
    src: start_server.sh
    dest: "{{ minecraft_install_folder }}"
    owner: "{{ minecraft_service_user }}"
    group: "{{ minecraft_service_user }}"
    mode: 0744
  become: true
  notify:
    - restart minecraft-service

- name: Create Systemd service file
  template:
    src: service.service
    dest: "/etc/systemd/system/{{ minecraft_service_name }}.service"
    owner: "root"
    group: "root"
  become: true
  notify:
    - restart minecraft-service
