---
- name: "Debug info (distribution)"
  debug:
    msg: "{{ ansible_distribution }}"

- name: "Debug info (os family)"
  debug:
    msg: "{{ ansible_facts['os_family'] }}"

- name: "({{ ansible_distribution }})  Run Debian family"
  import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: "({{ ansible_distribution }})  Run Debian family"
  import_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

- name: "({{ ansible_distribution }})  Create service user"
  user:
    name: "{{ minecraft_service_user }}"
    system: true
    state: present
  become: true

- name: "({{ ansible_distribution }})  Create install folder"
  file:
    path: "{{ minecraft_install_folder }}"
    owner: "{{ minecraft_service_user }}"
    group: "{{ minecraft_service_user }}"
    state: directory
    mode: 0744
  become: true

- name: "({{ ansible_distribution }})  Prepare the eula.txt file"
  copy:
    content: "eula=true"
    dest: "{{ minecraft_install_folder }}/eula.txt"
    owner: "{{ minecraft_service_user }}"
    group: "{{ minecraft_service_user }}"
  become: true
  notify:
    - restart minecraft-service

- name: "({{ ansible_distribution }})  Getting the server JAR file"
  get_url:
    url: "{{ minecraft_server_download_url }}"
    dest: "{{ minecraft_install_folder }}"
    owner: "{{ minecraft_service_user }}"
    group: "{{ minecraft_service_user }}"
    mode: 0744
  become: true
  notify:
    - restart minecraft-service

- name: "({{ ansible_distribution }})  Setting up server.properties file"
  template:
    src: server.properties
    dest: "{{ minecraft_install_folder }}"
    owner: "{{ minecraft_service_user }}"
    group: "{{ minecraft_service_user }}"
    mode: 0744
  become: true
  tags:
    - molecule-idempotence-notest
  notify:
    - restart minecraft-service

- name: "({{ ansible_distribution }})  Setting up startup script"
  template:
    src: start_server.sh
    dest: "{{ minecraft_install_folder }}"
    owner: "{{ minecraft_service_user }}"
    group: "{{ minecraft_service_user }}"
    mode: 0744
  become: true
  notify:
    - restart minecraft-service

- name: "({{ ansible_distribution }})  Create Systemd service file"
  template:
    src: service.service
    dest: "/etc/systemd/system/{{ minecraft_service_name }}.service"
    owner: "root"
    group: "root"
  become: true
  notify:
    - restart minecraft-service
